### ISSUE TITLE
Locked DLL

### ISSUE THREAD

**Issue by jsoysouvanh** [fungos/cr#34]
Hello,

I'm working on MSVC and I am trying to make a really simple 3 files project work, but I have a problem of a locked dll. I've pretty much copy-pasted the basic sample. When I try to regenerate the DLL after modification while my host executable is running, it tells me the DLL can't be overwritten because it is used somewhere. The lib seems to copy the .dll and .pdb properly, but both the original and the copy are used by the executable (I tried to remove them at runtime to make sure they were used). Nobody's complaining about such an issue so I guess I have misunderstood something here.

**Comment by fungos** [comment]
Hi! So you tried all other suggestions from other issues? I just merged a PR fixing a bug that caused lock, can you check if this works? Otherwise, double check your project settings to be sure nothing else is injecting dll references anywere.

**Comment by Angelysse** [comment]
Yes, I've tried other issues suggestions. The merge doesn't seem to solve my problem.
I'll give it some more tries in the in-coming days and keep you updated.

**Comment by fungos** [comment]
Closing due inactivity, thank you.
